---

- name: Loop over modify_interface
  ansible.builtin.include_tasks:
    file: for each.yml
  loop: "{{ modify_interface }}"
  loop_control:
    index_var: idx
  when: not debug

- name: Debug modify_interface
  ansible.builtin.include_tasks:
    file: .dbg.yml
  loop: "{{ modify_interface }}"
  loop_control:
    index_var: idx
  when: debug